name: blackbird blog
favicon: null
layout_spectrum: 0.36324074235744774
typography_spectrum: 0.21920054056681693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14079365646466613
  lightness: 0.5553320988547057
  saturation: 0.6092282508034259
  rhythmicContrast: 0.4328632822725922
purpose: []
